#!/bin/sh
#
# hwtest        Starts hwtest.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

start() {
	echo -n "Starting hwtest: "
	/bin/sleep 5 # Hacky wait for wifi modules to initialize
	/usr/bin/hwtest || /sbin/poweroff
	echo "OK"
}
stop() {
	echo -n "Stopping hwtest: "
	killall hwtest
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

